print( 'Operadores Relacionales\n' )
print( 'Igual que "=="' )
print( 'Diferente de "!="' )
print( 'Mayor que ">"' )
print( 'Mayor o igual que ">="' )
print( 'Menor que "<"' )
print( 'Menor o igual que "<="' )
print( '\n' )

print( 'Operadores Logicos\n' )
print( 'Negacion "not"' )
print( 'Conjuncion "and"' )
print( 'Disyuncion "or"' )